name: Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5        # checks out your code
      - uses: actions/setup-node@v4      # sets up Node.js
        with:
          node-version: '20'
      - run: npm install                 # install dependencies
      - run: npm test                    # run tests
